features = [
    # "dayofyear",
    # "lat",
    # "lon",
    # "hour",
    # "aod_terra",
    # "aod_aqua",
    # "aod_aqua_terra_mean",
    # "dayofweek",
    # "sunday",
    # "saturday",
    # "is_day",
    # "elevation",
    # 'pop_1km',
    # 'pop_2km',
    # 'pop_3km',
    # 'pop_4km',
    'pop_5km',
    # 'pop_10km',
    # "WS_MpS",
    # "WS_MpS_LAY0",
    # "WS_MpS_LAY19",
    # "WS_MpS_LAYdiff",
    # "WS_MpS_3d",
    'd_motorway',
    # 'TSURF_K',
    # 'SNOWEW_M',
    # 'SNOWAGE_HR',
    # 'PRATE_MMpH',
    # 'CLOUD_OD',
    # 'U10_MpS',
    # 'V10_MpS',
    # 'T2_K',
    # 'SWSFC_WpM2',
    # 'SOLM_M3pM3',
    # 'CLDTOP_KM',
    # 'CAPE',
    'PBL_WRF_M',
    # 'PBL_YSU_M',
    # 'ZGRID_M_LAY0',
    # 'ZGRID_M_LAY19',
    # 'ZGRID_M_LAYdiff',
    # 'ZGRID_M_3d',
    # 'PRESS_MB_LAY0',
    # 'PRESS_MB_LAY19',
    # 'PRESS_MB_LAYdiff',
    # 'PRESS_MB_3d',
    'TEMP_K_LAY0',
    # 'TEMP_K_LAY19',
    # 'TEMP_K_LAYdiff',
    # 'TEMP_K_3d',
    # 'HUMID_PPM_LAY0',
    # 'HUMID_PPM_LAY19',
    # 'HUMID_PPM_LAYdiff',
    # 'HUMID_PPM_3d',
    # 'UWIND_MpS_LAY0',
    # 'UWIND_MpS_LAY19',
    # 'UWIND_MpS_LAYdiff',
    # 'UWIND_MpS_3d',
    # 'VWIND_MpS_LAY0',
    # 'VWIND_MpS_LAY19',
    # 'VWIND_MpS_LAYdiff',
    # 'VWIND_MpS_3d',
    # "t_diff",
]
root_dir = "/opt/aqmsp_models"
seed = 0
target = "PM2.5"
